# Generated by Django 4.1.2 on 2022-10-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='modified_by',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_by',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
