# Generated by Django 4.1.2 on 2022-10-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_modified_by_alter_project_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='project',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
